/**
 * ResultsPanel Component
 * 
 * Displays calculated results in visually striking, color-coded cards.
 * Shows a placeholder state when no results are available.
 * Includes "Copy Results" and "Download PDF" action buttons.
 * 
 * @param {object|null} results — Calculated results object or null
 */
import { useState, useCallback } from 'react';
import './ResultsPanel.css';

/**
 * Format a number as Indian Rupee currency.
 */
const formatCurrency = (value) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
};

/**
 * Format a percentage value.
 */
const formatPercent = (value) => {
  return `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`;
};

/**
 * Format ROAS value.
 */
const formatRoas = (value) => {
  return `${value.toFixed(2)}x`;
};

const ResultsPanel = ({ results }) => {
  // Copy button feedback state
  const [copyStatus, setCopyStatus] = useState('idle'); // 'idle' | 'copied'

  /**
   * Copy results as formatted text to the clipboard.
   */
  const handleCopy = useCallback(async () => {
    if (!results) return;

    const text = [
      '═══════════════════════════════════════',
      '  SHOPIFY PROFIT CALCULATOR — RESULTS',
      '═══════════════════════════════════════',
      '',
      `  Revenue:              ${formatCurrency(results.revenue)}`,
      `  Total Cost:           ${formatCurrency(results.totalCost)}`,
      `  Net Profit:           ${formatCurrency(results.netProfit)}`,
      `  Profit Margin:        ${formatPercent(results.profitMargin)}`,
      `  Break-Even ROAS:      ${formatRoas(results.breakEvenRoas)}`,
      '',
      `  Gateway Fee Deducted: ${formatCurrency(results.gatewayFeeAmount)}`,
      '',
      '───────────────────────────────────────',
      '  Generated by ProfitCalc',
      '  Built for Digital Heroes',
      '═══════════════════════════════════════',
    ].join('\n');

    try {
      await navigator.clipboard.writeText(text);
      setCopyStatus('copied');
      setTimeout(() => setCopyStatus('idle'), 2000);
    } catch {
      // Fallback for browsers that don't support clipboard API
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopyStatus('copied');
      setTimeout(() => setCopyStatus('idle'), 2000);
    }
  }, [results]);

  /**
   * Generate and download a professionally formatted PDF of the results.
   * Uses dynamic import to lazy-load jsPDF only when needed.
   */
  const handleDownloadPDF = useCallback(async () => {
    if (!results) return;

    // Lazy-load jsPDF — keeps initial bundle small
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();
    const isProfit = results.netProfit >= 0;
    const pageWidth = doc.internal.pageSize.getWidth();

    // ---- Header bar ----
    doc.setFillColor(0, 76, 63); // Dark green
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Shopify Profit Calculator', pageWidth / 2, 20, { align: 'center' });
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Product Profitability Report', pageWidth / 2, 30, { align: 'center' });

    // ---- Date ----
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, pageWidth / 2, 50, { align: 'center' });

    // ---- Results table ----
    let y = 65;
    const leftMargin = 30;
    const valueX = 130;

    // Helper to draw a result row
    const drawRow = (label, value, highlight = false) => {
      if (highlight) {
        doc.setFillColor(isProfit ? 230 : 255, isProfit ? 248 : 235, isProfit ? 240 : 235);
        doc.roundedRect(leftMargin - 5, y - 6, pageWidth - 50, 14, 3, 3, 'F');
      }
      doc.setTextColor(80, 80, 80);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(label, leftMargin, y);
      doc.setTextColor(30, 30, 30);
      doc.setFont('helvetica', 'bold');
      doc.text(value, valueX, y);
      y += 18;
    };

    drawRow('Revenue', formatCurrency(results.revenue));
    drawRow('Total Cost', formatCurrency(results.totalCost));
    drawRow('Net Profit', formatCurrency(results.netProfit), true);
    drawRow('Profit Margin', formatPercent(results.profitMargin), true);
    drawRow('Break-Even ROAS', formatRoas(results.breakEvenRoas));

    // Separator
    y += 4;
    doc.setDrawColor(220, 220, 220);
    doc.line(leftMargin, y, pageWidth - leftMargin, y);
    y += 14;

    // Gateway fee detail
    doc.setTextColor(120, 120, 120);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Payment Gateway Fee Deducted:', leftMargin, y);
    doc.setFont('helvetica', 'bold');
    doc.text(formatCurrency(results.gatewayFeeAmount), valueX, y);

    // ---- Status message ----
    y += 30;
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    if (isProfit) {
      doc.setTextColor(0, 128, 96);
      doc.text(`You earn ${formatCurrency(results.netProfit)} profit per sale`, pageWidth / 2, y, { align: 'center' });
    } else {
      doc.setTextColor(228, 87, 46);
      doc.text(`You lose ${formatCurrency(Math.abs(results.netProfit))} per sale`, pageWidth / 2, y, { align: 'center' });
    }

    // ---- Footer ----
    const footerY = 270;
    doc.setDrawColor(200, 200, 200);
    doc.line(20, footerY, pageWidth - 20, footerY);
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Purvesh Khandare  |  purveshkhandare083@gmail.com  |  Built for Digital Heroes', pageWidth / 2, footerY + 8, { align: 'center' });

    doc.save('profit-calculator-results.pdf');
  }, [results]);

  // Placeholder state when no inputs are provided
  if (!results) {
    return (
      <div className="results-panel results-panel--empty" id="results" aria-label="Results section">
        <div className="results-panel__empty-state">
          <div className="results-panel__empty-icon" aria-hidden="true">
            <svg width="56" height="56" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <rect x="4" y="2" width="16" height="20" rx="2" />
              <line x1="8" y1="6" x2="16" y2="6" />
              <line x1="8" y1="10" x2="16" y2="10" />
              <line x1="8" y1="14" x2="12" y2="14" />
            </svg>
          </div>
          <h3 className="results-panel__empty-title">Your Results Will Appear Here</h3>
          <p className="results-panel__empty-text">
            Enter a selling price to see your calculated profit, margin, and break-even ROAS.
          </p>
        </div>
      </div>
    );
  }

  const isProfit = results.netProfit >= 0;

  // Result cards configuration
  const cards = [
    {
      id: 'revenue',
      label: 'Revenue',
      value: formatCurrency(results.revenue),
      icon: (
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <line x1="12" y1="1" x2="12" y2="23" /><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
        </svg>
      ),
      gradient: 'results-card--revenue',
      description: 'Total income from selling price',
    },
    {
      id: 'total-cost',
      label: 'Total Cost',
      value: formatCurrency(results.totalCost),
      icon: (
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
        </svg>
      ),
      gradient: 'results-card--cost',
      description: 'All costs combined',
    },
    {
      id: 'net-profit',
      label: 'Net Profit',
      value: formatCurrency(results.netProfit),
      icon: (
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <polyline points="23 6 13.5 15.5 8.5 10.5 1 18" /><polyline points="17 6 23 6 23 12" />
        </svg>
      ),
      gradient: isProfit ? 'results-card--profit' : 'results-card--loss',
      description: isProfit ? 'You\'re making profit! 🎉' : 'You\'re at a loss ⚠️',
      highlight: true,
    },
    {
      id: 'profit-margin',
      label: 'Profit Margin',
      value: formatPercent(results.profitMargin),
      icon: (
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="10" /><path d="M8 12l3 3 5-5" />
        </svg>
      ),
      gradient: results.profitMargin >= 30
        ? 'results-card--profit'
        : results.profitMargin >= 0
          ? 'results-card--roas'
          : 'results-card--loss',
      description: results.profitMargin >= 30
        ? 'Healthy margin ✅'
        : results.profitMargin >= 0
          ? 'Below recommended 30%'
          : 'Negative margin ⚠️',
    },
    {
      id: 'break-even-roas',
      label: 'Break-Even ROAS',
      value: formatRoas(results.breakEvenRoas),
      icon: (
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M12 20V10" /><path d="M18 20V4" /><path d="M6 20v-4" />
        </svg>
      ),
      gradient: 'results-card--roas',
      description: 'Minimum ROAS to break even',
    },
  ];

  return (
    <div className="results-panel" id="results" aria-label="Calculation results">
      {/* Action buttons — Copy & Download PDF */}
      <div className="results-panel__actions">
        <button
          type="button"
          className={`results-action-btn results-action-btn--copy ${copyStatus === 'copied' ? 'results-action-btn--success' : ''}`}
          onClick={handleCopy}
          aria-label="Copy results to clipboard"
        >
          {copyStatus === 'copied' ? (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <polyline points="20 6 9 17 4 12" />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
              </svg>
              Copy Results
            </>
          )}
        </button>

        <button
          type="button"
          className="results-action-btn results-action-btn--pdf"
          onClick={handleDownloadPDF}
          aria-label="Download results as PDF"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" />
          </svg>
          Download PDF
        </button>
      </div>

      {/* Status banner */}
      <div className={`results-panel__status ${isProfit ? 'results-panel__status--profit' : 'results-panel__status--loss'}`}>
        <span className="results-panel__status-icon" aria-hidden="true">
          {isProfit ? '📈' : '📉'}
        </span>
        <span className="results-panel__status-text">
          {isProfit
            ? `You earn ${formatCurrency(results.netProfit)} profit per sale`
            : `You lose ${formatCurrency(Math.abs(results.netProfit))} per sale`
          }
        </span>
      </div>

      {/* Result cards */}
      <div className="results-panel__cards">
        {cards.map((card, index) => (
          <div
            key={card.id}
            className={`results-card ${card.gradient} ${card.highlight ? 'results-card--highlight' : ''}`}
            style={{ animationDelay: `${index * 0.08}s` }}
            role="article"
            aria-label={`${card.label}: ${card.value}`}
          >
            <div className="results-card__header">
              <span className="results-card__icon" aria-hidden="true">{card.icon}</span>
              <span className="results-card__label">{card.label}</span>
            </div>
            <div className="results-card__value">{card.value}</div>
            <p className="results-card__description">{card.description}</p>
          </div>
        ))}
      </div>

      {/* Gateway fee detail */}
      <div className="results-panel__detail">
        <span className="results-panel__detail-label">Payment Gateway Fee Deducted:</span>
        <span className="results-panel__detail-value">{formatCurrency(results.gatewayFeeAmount)}</span>
      </div>
    </div>
  );
};

export default ResultsPanel;
